### ISSUE TITLE
Map type of Variable inside a Non-JAVA Type Bean

### ISSUE THREAD

**Issue by kingshuknandy2016** [remondis-it/pact-consumer-builder#27]
Have  seen that, ConsumerExpects.type(JavaTypeBean.class) can handle any type of variables. like another object, or String, or int or List.
But is there a way to handle Map type of Variable inside the JavaTypeBean.class.
Please help

**Comment by schuettec** [comment]
Sorry Maps are currently not supported. You can translate a map manually by adding a specific field configuration. Maybe we support Maps in the future.
