### ISSUE TITLE
Java array structure

### ISSUE THREAD

**Issue by rilo03** [remondis-it/pact-consumer-builder#28]
Hi, I ran into a problem generating pact files from Java list, the details:

https://github.com/DiUS/pact-jvm/issues/1185

Any help would be appreciated.

**Comment by schuettec** [comment]
Hi thanks for your post. I'm on it :)

**Comment by schuettec** [comment]
Hm this was fixed with #12 and I'm not able to reproduce this.
I created a branch #29 with your test and the pact-consumer-builder produces the right output.
Please double check your `pact-consumer-builder` version and let me know if you could fix it.
