### ISSUE TITLE
Upload lib to the central repository

### ISSUE THREAD

**Issue by jbrundege** [remondis-it/pact-consumer-builder#8]
Thank you for writing this much needed utility! If the current version is stable it would very helpful to upload it to the maven central repo (which is a prereq for us to use it).

**Comment by schuettec** [comment]
Hi good to hear! Thank you!

The library is available through Maven Central. You may follow the badge in the Readme.

In case the badge is not working check out
https://search.maven.org/artifact/com.remondis.cdc/pact-consumer-builder/0.0.2/jar

**Comment by jbrundege** [comment]
Fantastic, don't know why I missed it, but I've got it now. 

In my search to find something like this I came across this post:
https://stackoverflow.com/questions/48339994/pact-contract-test-how-to-generate-dynamic-pactdsljsonbody-using-json-value
You may want to mention this library as it exactly answers the user's question. I'm happy to add that post if you don't want to. 

Thanks again!

**Comment by schuettec** [comment]
Sounds good to me. Feel free to add the post :)



jbrundege <notifications@github.com> schrieb am Mo., 9. Sep. 2019, 23:51:
